version: '3'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    expose:
      - ${HTTP_SERVER_PORT}
    ports:
      - 80:${HTTP_SERVER_PORT}
#      - "443:443"
    command: "./main serve"
    volumes:
      - ./migrations:/migrations
      - ./GeoLite2-Country.mmdb:/GeoLite2-Country.mmdb
    links:
      - db
    depends_on:
      - db

  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - ./.env
    expose:
      - ${HTTP_SERVER_PORT}
    ports:
      - 8080:${HTTP_SERVER_PORT}
#      - "443:443"
#    command: "./main serve"
    volumes:
      - ./:/home/builder
      - ./GeoLite2-Country.mmdb:/GeoLite2-Country.mmdb
    links:
      - db
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - 5432:${DB_PORT}
    volumes:
      - psql-storage:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

volumes:
  psql-storage:
