// Code generated by MockGen. DO NOT EDIT.
// Source: domain/interactor/click_handler.go
//
// Generated by this command:
//
//	mockgen -package=mocks -destination=mocks/mock_click_handler.go -source=domain/interactor/click_handler.go ClickHandlerInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/lroman242/redirector/domain/dto"
	entity "github.com/lroman242/redirector/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockClickHandlerInterface is a mock of ClickHandlerInterface interface.
type MockClickHandlerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockClickHandlerInterfaceMockRecorder
	isgomock struct{}
}

// MockClickHandlerInterfaceMockRecorder is the mock recorder for MockClickHandlerInterface.
type MockClickHandlerInterfaceMockRecorder struct {
	mock *MockClickHandlerInterface
}

// NewMockClickHandlerInterface creates a new mock instance.
func NewMockClickHandlerInterface(ctrl *gomock.Controller) *MockClickHandlerInterface {
	mock := &MockClickHandlerInterface{ctrl: ctrl}
	mock.recorder = &MockClickHandlerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClickHandlerInterface) EXPECT() *MockClickHandlerInterfaceMockRecorder {
	return m.recorder
}

// HandleClick mocks base method.
func (m *MockClickHandlerInterface) HandleClick(ctx context.Context, click *entity.Click) <-chan *dto.ClickProcessingResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleClick", ctx, click)
	ret0, _ := ret[0].(<-chan *dto.ClickProcessingResult)
	return ret0
}

// HandleClick indicates an expected call of HandleClick.
func (mr *MockClickHandlerInterfaceMockRecorder) HandleClick(ctx, click any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleClick", reflect.TypeOf((*MockClickHandlerInterface)(nil).HandleClick), ctx, click)
}
